# Generated by Django 5.2.17 on 2026-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('window_count', models.PositiveIntegerField(default=0)),
                ('day', models.DateField(auto_now_add=True)),
                ('day_downloads', models.PositiveIntegerField(default=0)),
                ('active_requests', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client usage',
                'verbose_name_plural': 'Client usage',
            },
        ),
        migrations.CreateModel(
            name='RateLimitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Turn rate limiting on or off for the whole site.')),
                ('max_concurrent_requests', models.PositiveIntegerField(default=1, help_text='How many API requests one client (IP) may run at the same time.')),
                ('max_requests_per_window', models.PositiveIntegerField(default=10, help_text='Maximum API requests per client within the window below.')),
                ('window_seconds', models.PositiveIntegerField(default=60, help_text='Length of the request window in seconds.')),
                ('max_downloads_per_day', models.PositiveIntegerField(default=20, help_text='Maximum video/audio/transcript downloads per client per day.')),
            ],
            options={
                'verbose_name': 'Rate limit configuration',
                'verbose_name_plural': 'Rate limit configuration',
            },
        ),
    ]
