# Generated by Django 5.2.17 on 2026-08-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusage',
            name='downloaded_links',
            field=models.JSONField(blank=True, default=list, help_text='Video IDs downloaded today by this client (one entry per link).'),
        ),
        migrations.AlterField(
            model_name='ratelimitconfig',
            name='max_downloads_per_day',
            field=models.PositiveIntegerField(default=20, help_text='Maximum distinct video links a client may download per day. Downloading video, audio, and transcript for one link counts once.'),
        ),
    ]
