# Generated by Django 5.2.17 on 2026-08-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("downloader", "0002_clientusage_downloaded_links_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ClientUsage"),
        migrations.DeleteModel(name="RateLimitConfig"),
    ]
